# add_newline = false
#
# [line_break]
# disabled = true
# format = """$all$fill$kubernetes"""
# right_format = "$kubernetes"

[character]
success_symbol = "[ ](bold green)"
error_symbol = "[ ](bold red)"
vicmd_symbol = "[ ](bold blue)"
# success_symbol = "[➜ ](bold green)"
# error_symbol = "[➜ ](bold red)"
# vicmd_symbol = "[➜ ](bold blue)"
# success_symbol = "[ ](bold green)"
# error_symbol = "[ ](bold red)"
# vicmd_symbol = "[ ](bold blue)"
# success_symbol = "[ ](bold green)"
# error_symbol = "[ ](bold red)"
# vicmd_symbol = "[ ](bold blue)"
# success_symbol = "[ ](bold green)"
# error_symbol = "[ ](bold red)"
# vicmd_symbol = "[ ](bold blue)"
[container]
disabled = true

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = "  "
truncation_length = 10
format = '[ $path]($style)[$read_only]($read_only_style) '

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

#[git_branch]
#symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "

[kubernetes]
disabled = false
format = '[$symbol$context](purple)[( $namespace)](yellow) in '
symbol = "⎈ "

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"
